### PR TITLE
Reduce dependencies

### PR DESCRIPTION
**Pull request by jplatte**

### CODE REVIEW

**Comment by jplatte** [comment]
codecov failed with

```
/usr/bin/env: 'python': No such file or directory
```

**Comment by asomers** [comment]
This LGTM, but it needs to be rebased.

**Comment by jplatte** [comment]
Could you release a new version now? I can't use `[patch]` to update to the new version since it's an indirect dependency and `Cargo.toml` declares a `version` that doesn't exist on crates.io.

**Comment by asomers** [comment]
I will do it soon.  But first I'm trying to convince myself whether the other Send and Sync implementation are correct.

**Comment by asomers** [comment]
BTW @jplatte I removed the -dev suffix.  It's been annoying me too.

**Pull request merged**
